services:
  discord_music_bot:
    image: ghcr.io/bnfone/discord-bot-evomusic:latest
    container_name: discord_music_bot
    networks:
      - discordbot_evomusic
    volumes:
      - ./data:/dist/data
    environment:
      - TOKEN=your_discord_bot_token
      - SPOTIFY_CLIENT_ID=your_spotify_client_id
      - SPOTIFY_CLIENT_SECRET=your_spotify_client_secret
      - MAX_PLAYLIST_SIZE=100
      - PRUNING=false
      - STAY_TIME=30
      - DEFAULT_VOLUME=100
      - LOCALE=en
      - PIPED_API_URL=https://pipedapi.example.com
      - PIPED_FALLBACK=true
    restart: always

networks:
  discordbot_evomusic:
    enable_ipv6: true
    driver: bridge
